### ISSUE TITLE
Can it show higher precision of accuracy in workbench?

### ISSUE THREAD

**Issue by 0400H** [openvinotoolkit/workbench_aux#7]
![workbench](https://user-images.githubusercontent.com/16373603/104103803-121ce400-52df-11eb-851e-b7a0a1e85ad2.png)

The position marked in the picture has only one precision, can it show higher precision?
Looking forward to future updates.

**Comment by 0400H** [comment]
And why can't I achieve the expected 0.5% accuracy drop but more?

**Comment by vishniakov-nikolai** [comment]
Hello @0400H! Could you tell me which version of DL Workbench you are using?
You can find the version number in system info by clicking on the settings icon (on the right in the header panel).

**Comment by 0400H** [comment]
> Hello @0400H! Could you tell me which version of DL Workbench you are using?
> You can find the version number in system info by clicking on the settings icon (on the right in the header panel).

I do not keep a record of the version, but the version should be at the same date while the issue was mentioned (2021/1/10).

It is recommended to keep at least 3 significant number such as 0.xxx

**Comment by vishniakov-nikolai** [comment]
In the latest version of DL Workbench (2021.4), the accuracy is displayed as a number from 0 to 100 with 2 digits precision.

**Comment by 0400H** [comment]
> In the latest version of DL Workbench (2021.4), the accuracy is displayed as a number from 0 to 100 with 2 digits precision.

Thanks for your reply.
